"""add_missing_tables

Revision ID: 2ef08ee94771
Revises: 46b08465b370
Create Date: 2026-06-06 06:41:58.232485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ef08ee94771'
down_revision: Union[str, None] = '46b08465b370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeding_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeding_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('flock_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feed_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quantity_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name='feeding_records_flock_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feeding_records_pkey')
    )
    # ### end Alembic commands ###
