"""add veterinarian to treatments

Revision ID: 31a30283c769
Revises: 74bbb5852901
Create Date: 2026-06-08 13:27:35.264250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a30283c769'
down_revision: Union[str, None] = '74bbb5852901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatments', sa.Column('veterinarian_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'treatments', 'users', ['veterinarian_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatments', type_='foreignkey')
    op.drop_column('treatments', 'veterinarian_id')
    # ### end Alembic commands ###
