"""add_timestamps_to_farms

Revision ID: 41ac67f63c3f
Revises: 2a1ff694bcf4
Create Date: 2026-06-10 01:22:33.135194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ac67f63c3f'
down_revision: Union[str, None] = '2a1ff694bcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
