"""add_feeding_records_and_egg_collections

Revision ID: 46b08465b370
Revises: 2db24aec48f8
Create Date: 2026-06-06 06:15:43.558441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b08465b370'
down_revision: Union[str, None] = '2db24aec48f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
