"""add_suppliers_and_stock_tables

Revision ID: 5705e034a3c8
Revises: 2ef08ee94771
Create Date: 2026-06-06 16:23:51.239335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5705e034a3c8'
down_revision: Union[str, None] = '2ef08ee94771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeding_records')
    op.alter_column('flocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('stock_items', sa.Column('supplier_id', sa.UUID(), nullable=True))
    op.add_column('stock_items', sa.Column('unit_price', sa.Float(), nullable=True))
    op.add_column('stock_items', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'stock_items', 'suppliers', ['supplier_id'], ['id'])
    op.add_column('stock_movements', sa.Column('operator_id', sa.UUID(), nullable=False))
    op.add_column('stock_movements', sa.Column('operator_name', sa.String(length=255), nullable=False))
    op.add_column('stock_movements', sa.Column('movement_date', sa.DateTime(), nullable=False))
    op.add_column('stock_movements', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('stock_movements', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('stock_movements', 'comment',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'stock_movements', 'users', ['operator_id'], ['id'])
    op.drop_column('stock_movements', 'stock_item_name')
    op.drop_column('stock_movements', 'operator')
    op.drop_column('stock_movements', 'date')
    op.alter_column('suppliers', 'address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('suppliers', 'supplied_categories',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('suppliers', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('suppliers', 'farm_ids')
    op.alter_column('weighings', 'weights',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=sa.Text(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::double precision[]"))
    op.alter_column('weighings', 'min_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weighings', 'max_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weighings', 'std_deviation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weighings', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('weighings', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('weighings', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('weighings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('weighings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weighings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('weighings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('weighings', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('weighings', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('weighings', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('weighings', 'std_deviation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weighings', 'max_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weighings', 'min_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weighings', 'weights',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::double precision[]"))
    op.add_column('suppliers', sa.Column('farm_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False))
    op.alter_column('suppliers', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('suppliers', 'supplied_categories',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('suppliers', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('stock_movements', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('stock_movements', sa.Column('operator', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('stock_movements', sa.Column('stock_item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.alter_column('stock_movements', 'comment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('stock_movements', 'type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('stock_movements', 'created_at')
    op.drop_column('stock_movements', 'movement_date')
    op.drop_column('stock_movements', 'operator_name')
    op.drop_column('stock_movements', 'operator_id')
    op.drop_constraint(None, 'stock_items', type_='foreignkey')
    op.drop_column('stock_items', 'notes')
    op.drop_column('stock_items', 'unit_price')
    op.drop_column('stock_items', 'supplier_id')
    op.alter_column('flocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table('feeding_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('flock_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feed_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quantity_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name='feeding_records_flock_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feeding_records_pkey')
    )
    # ### end Alembic commands ###
