"""create_farm_members_table

Revision ID: 64e5dbf683a9
Revises: 6d7de7da249a
Create Date: 2026-05-30 21:57:47.584397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e5dbf683a9'
down_revision: Union[str, None] = '6d7de7da249a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
