"""add_feeding_records_table

Revision ID: 7485adc5c54f
Revises: d5abcd2e452f
Create Date: 2026-06-10 18:10:10.775020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7485adc5c54f'
down_revision: Union[str, None] = 'd5abcd2e452f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
