"""fix disease relationships

Revision ID: 74bbb5852901
Revises: 865f5866ad5c
Create Date: 2026-06-08 13:15:04.289362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74bbb5852901'
down_revision: Union[str, None] = '865f5866ad5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('treatments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('treatments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('vaccinations', 'disease_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('vaccinations', 'administration_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('vaccinations', 'next_due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('vaccinations', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('vaccinations_veterinarian_id_fkey', 'vaccinations', type_='foreignkey')
    op.drop_column('vaccinations', 'veterinarian_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccinations', sa.Column('veterinarian_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('vaccinations_veterinarian_id_fkey', 'vaccinations', 'users', ['veterinarian_id'], ['id'])
    op.alter_column('vaccinations', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('vaccinations', 'next_due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('vaccinations', 'administration_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('vaccinations', 'disease_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('treatments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('treatments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
