"""Add egg_collections table

Revision ID: 7a06f030f132
Revises: 7a2d4ea965d1
Create Date: 2026-06-05 20:36:22.358284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a06f030f132'
down_revision: Union[str, None] = '7a2d4ea965d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egg_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('egg_count', sa.Integer(), nullable=False),
    sa.Column('egg_size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='eggsize'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('collection_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('flocks', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('fk_flock_espece', 'flocks', type_='foreignkey')
    op.drop_column('flocks', 'espece_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flocks', sa.Column('espece_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_flock_espece', 'flocks', 'especes', ['espece_id'], ['id'])
    op.alter_column('flocks', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_table('egg_collections')
    # ### end Alembic commands ###
