"""Add feeding records and split functionality

Revision ID: 7a2d4ea965d1
Revises: 12cbfd23d662
Create Date: 2026-06-05 11:59:52.722758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a2d4ea965d1'
down_revision: Union[str, None] = '12cbfd23d662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('farms', 'poultry_types',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String(length=50)),
               nullable=False)
    op.drop_column('farms', 'type')
    op.add_column('flocks', sa.Column('parent_flock_id', sa.UUID(), nullable=True))
    op.add_column('flocks', sa.Column('is_quarantine', sa.Boolean(), nullable=True))
    op.alter_column('flocks', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_foreign_key(None, 'flocks', 'flocks', ['parent_flock_id'], ['id'])
    op.alter_column('poultry_houses', 'has_automation',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poultry_houses', 'has_automation',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'flocks', type_='foreignkey')
    op.alter_column('flocks', 'start_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('flocks', 'is_quarantine')
    op.drop_column('flocks', 'parent_flock_id')
    op.add_column('farms', sa.Column('type', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=False))
    op.alter_column('farms', 'poultry_types',
               existing_type=sa.ARRAY(sa.String(length=50)),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    # ### end Alembic commands ###
