"""add_stock_item_id_to_feeding_records

Revision ID: 81b96bc9b8e2
Revises: c748b466ab77
Create Date: 2026-06-12 07:32:17.631436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b96bc9b8e2'
down_revision: Union[str, None] = 'c748b466ab77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
