"""add_vaccinations_and_treatments_tables

Revision ID: 865f5866ad5c
Revises: 89a2c4960d62
Create Date: 2026-06-08 13:03:51.616880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '865f5866ad5c'
down_revision: Union[str, None] = '89a2c4960d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('treatments', 'disease_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('treatments', 'dosage',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('treatments', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('treatments', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('treatments', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('treatments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('treatments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('treatments_veterinarian_id_fkey', 'treatments', type_='foreignkey')
    op.drop_column('treatments', 'veterinarian_id')
    op.drop_column('treatments', 'animals_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatments', sa.Column('animals_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('treatments', sa.Column('veterinarian_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('treatments_veterinarian_id_fkey', 'treatments', 'users', ['veterinarian_id'], ['id'])
    op.alter_column('treatments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('treatments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('treatments', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('treatments', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('treatments', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('treatments', 'dosage',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('treatments', 'disease_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
