"""add_feed_sub_type_and_missing_fields_to_stock_items

Revision ID: 89a2c4960d62
Revises: 13b74b6f5f31
Create Date: 2026-06-08 07:01:51.122462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89a2c4960d62'
down_revision: Union[str, None] = '13b74b6f5f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feeding_records_date', table_name='feeding_records')
    op.drop_index('idx_feeding_records_flock_id', table_name='feeding_records')
    op.drop_table('feeding_records')
    op.alter_column('stock_items', 'feed_sub_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type d aliment: starter, grower, finisher (uniquement pour category=feed)',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_items', 'feed_sub_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type d aliment: starter, grower, finisher (uniquement pour category=feed)',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.create_table('feeding_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('flock_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feed_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type daliment: starter, grower, finisher'),
    sa.Column('quantity_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Quantité en kilogrammes'),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name='feeding_records_flock_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feeding_records_pkey'),
    comment='Enregistrements des alimentations des lots'
    )
    op.create_index('idx_feeding_records_flock_id', 'feeding_records', ['flock_id'], unique=False)
    op.create_index('idx_feeding_records_date', 'feeding_records', ['date'], unique=False)
    # ### end Alembic commands ###
