"""update_user_farm_relation

Revision ID: 8efe25ad07ee
Revises: f4043dd4a565
Create Date: 2026-05-30 21:46:10.530022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efe25ad07ee'
down_revision: Union[str, None] = 'f4043dd4a565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flocks', sa.Column('band_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'flocks', 'bands', ['band_id'], ['id'])
    op.add_column('sales', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'sales', 'users', ['user_id'], ['id'])
    op.add_column('sensor_reading', sa.Column('sensor_id', sa.UUID(), nullable=False))
    op.add_column('sensor_reading', sa.Column('sensor_name', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'sensor_reading', 'sensors', ['sensor_id'], ['id'])
    op.add_column('tasks', sa.Column('assigned_to', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    op.drop_constraint('users_farm_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'farms', ['farm_id'], ['id'])
    op.add_column('weighings', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint('weighings_agent_id_fkey', 'weighings', type_='foreignkey')
    op.create_foreign_key(None, 'weighings', 'users', ['user_id'], ['id'])
    op.drop_column('weighings', 'agent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weighings', sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'weighings', type_='foreignkey')
    op.create_foreign_key('weighings_agent_id_fkey', 'weighings', 'users', ['agent_id'], ['id'])
    op.drop_column('weighings', 'user_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_farm_id_fkey', 'users', 'farms', ['farm_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_to')
    op.drop_constraint(None, 'sensor_reading', type_='foreignkey')
    op.drop_column('sensor_reading', 'sensor_name')
    op.drop_column('sensor_reading', 'sensor_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'user_id')
    op.drop_constraint(None, 'flocks', type_='foreignkey')
    op.drop_column('flocks', 'band_id')
    # ### end Alembic commands ###
