"""fix_poultry_houses_timestamps

Revision ID: be7762020921
Revises: 31a30283c769
Create Date: 2026-06-09 11:52:47.382314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7762020921'
down_revision: Union[str, None] = '31a30283c769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccinations', 'veterinarian_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccinations', 'veterinarian_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
