"""add alerts relation

Revision ID: c4e4382cec83
Revises: ccc1357bafa0
Create Date: 2026-05-28 11:17:34.477768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e4382cec83'
down_revision: Union[str, None] = 'ccc1357bafa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'alerts', 'users', ['user_id'], ['id'])
    op.add_column('poultry_houses', sa.Column('automation_rules', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poultry_houses', 'automation_rules')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'user_id')
    # ### end Alembic commands ###
