"""add_stock_item_id_to_feeding_records

Revision ID: c748b466ab77
Revises: 7485adc5c54f
Create Date: 2026-06-11 13:53:36.442352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c748b466ab77'
down_revision: Union[str, None] = '7485adc5c54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feeding_records_date', table_name='feeding_records')
    op.drop_index('idx_feeding_records_flock_id', table_name='feeding_records')
    op.drop_table('feeding_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeding_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('flock_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feed_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quantity_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name='feeding_records_flock_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feeding_records_pkey')
    )
    op.create_index('idx_feeding_records_flock_id', 'feeding_records', ['flock_id'], unique=False)
    op.create_index('idx_feeding_records_date', 'feeding_records', ['date'], unique=False)
    # ### end Alembic commands ###
