"""add_feeding_records_table

Revision ID: d5abcd2e452f
Revises: 41ac67f63c3f
Create Date: 2026-06-10 18:05:38.145288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5abcd2e452f'
down_revision: Union[str, None] = '41ac67f63c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
