"""harmonize user and farm relations

Revision ID: f4043dd4a565
Revises: 7915e873363e
Create Date: 2026-05-28 12:02:23.468092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4043dd4a565'
down_revision: Union[str, None] = '7915e873363e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automation_rules')
    op.drop_column('poultry_houses', 'has_automation')
    op.drop_column('poultry_houses', 'automation_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poultry_houses', sa.Column('automation_rules', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.add_column('poultry_houses', sa.Column('has_automation', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('automation_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('poultry_house_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('schedule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['poultry_house_id'], ['poultry_houses.id'], name='automation_rules_poultry_house_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='automation_rules_pkey')
    )
    # ### end Alembic commands ###
